"""add program tables

Revision ID: 078b67ea30c8
Revises: a1b2c3d4e5f6
Create Date: 2026-07-15 21:38:39.851060

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "078b67ea30c8"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "program_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("goals", sa.JSON(), nullable=False),
        sa.Column("experience_levels", sa.JSON(), nullable=False),
        sa.Column("days_per_week_min", sa.Integer(), nullable=False),
        sa.Column("days_per_week_max", sa.Integer(), nullable=False),
        sa.Column("session_duration_min", sa.Integer(), nullable=False),
        sa.Column("session_duration_max", sa.Integer(), nullable=False),
        sa.Column("split", sa.JSON(), nullable=False),
        sa.Column("slot_rules", sa.JSON(), nullable=False),
        sa.Column("progression_ref", sa.JSON(), nullable=False),
        sa.Column("required_inputs", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_program_templates_slug"), "program_templates", ["slug"], unique=True)
    op.create_table(
        "workout_programs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("environment_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("focus", sa.String(length=50), nullable=True),
        sa.Column("status", sa.Enum("DRAFT", "ACTIVE", "ARCHIVED", name="programstatus"), nullable=False),
        sa.Column("duration_weeks", sa.Integer(), nullable=False),
        sa.Column("days_per_week", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("weight_unit", sa.String(length=3), nullable=False),
        sa.Column("constraints", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["training_environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["program_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workout_programs_user_id"), "workout_programs", ["user_id"], unique=False)
    op.create_table(
        "workouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("focus", sa.String(length=100), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["workout_programs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workouts_program_id"), "workouts", ["program_id"], unique=False)
    op.create_table(
        "workout_exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("fills_rule", sa.JSON(), nullable=False),
        sa.Column("sets", sa.Integer(), nullable=False),
        sa.Column("reps_min", sa.Integer(), nullable=False),
        sa.Column("reps_max", sa.Integer(), nullable=False),
        sa.Column("base_load", sa.Float(), nullable=True),
        sa.Column("rest_seconds", sa.Integer(), nullable=False),
        sa.Column("scheme_key", sa.String(length=50), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("is_user_swapped", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workout_exercises_workout_id"), "workout_exercises", ["workout_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workout_exercises_workout_id"), table_name="workout_exercises")
    op.drop_table("workout_exercises")
    op.drop_index(op.f("ix_workouts_program_id"), table_name="workouts")
    op.drop_table("workouts")
    op.drop_index(op.f("ix_workout_programs_user_id"), table_name="workout_programs")
    op.drop_table("workout_programs")
    op.drop_index(op.f("ix_program_templates_slug"), table_name="program_templates")
    op.drop_table("program_templates")
    # ### end Alembic commands ###
    sa.Enum(name="programstatus").drop(op.get_bind(), checkfirst=True)
