"""create workout logging tables

Revision ID: 1e522e5820b9
Revises: f0650953fd97
Create Date: 2026-07-22 17:35:33.688101

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e522e5820b9"
down_revision: Union[str, None] = "f0650953fd97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_workout_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("session_date", sa.DateTime(), nullable=False),
        sa.Column("readiness", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_workout_logs_session_date"), "user_workout_logs", ["session_date"], unique=False)
    op.create_index(op.f("ix_user_workout_logs_user_id"), "user_workout_logs", ["user_id"], unique=False)
    op.create_index(op.f("ix_user_workout_logs_workout_id"), "user_workout_logs", ["workout_id"], unique=False)
    op.create_table(
        "workout_set_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("workout_exercise_id", sa.Integer(), nullable=False),
        sa.Column("set_number", sa.Integer(), nullable=False),
        sa.Column("actual_weight", sa.Float(), nullable=True),
        sa.Column("actual_reps", sa.Integer(), nullable=True),
        sa.Column("actual_rpe", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workout_exercise_id"],
            ["workout_exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workout_set_logs_user_id"), "workout_set_logs", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_workout_set_logs_workout_exercise_id"), "workout_set_logs", ["workout_exercise_id"], unique=False
    )
    op.create_index(op.f("ix_workout_set_logs_workout_id"), "workout_set_logs", ["workout_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workout_set_logs_workout_id"), table_name="workout_set_logs")
    op.drop_index(op.f("ix_workout_set_logs_workout_exercise_id"), table_name="workout_set_logs")
    op.drop_index(op.f("ix_workout_set_logs_user_id"), table_name="workout_set_logs")
    op.drop_table("workout_set_logs")
    op.drop_index(op.f("ix_user_workout_logs_workout_id"), table_name="user_workout_logs")
    op.drop_index(op.f("ix_user_workout_logs_user_id"), table_name="user_workout_logs")
    op.drop_index(op.f("ix_user_workout_logs_session_date"), table_name="user_workout_logs")
    op.drop_table("user_workout_logs")
    # ### end Alembic commands ###
