"""add effort_method to workout_set_logs

Revision ID: 542417adc2ef
Revises: 1e522e5820b9
Create Date: 2026-07-23 03:24:12.508012

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "542417adc2ef"
down_revision: Union[str, None] = "1e522e5820b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workout_set_logs", sa.Column("effort_method", sa.String(length=20), server_default="rpe", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workout_set_logs", "effort_method")
    # ### end Alembic commands ###
