"""add model_version and ranking_weights_version to workout_programs

Revision ID: 6b1a2c3d4e5f
Revises: 542417adc2ef
Create Date: 2026-07-23 12:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b1a2c3d4e5f"
down_revision: Union[str, None] = "542417adc2ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workout_programs", sa.Column("model_version", sa.String(length=50), nullable=True))
    op.add_column("workout_programs", sa.Column("ranking_weights_version", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workout_programs", "ranking_weights_version")
    op.drop_column("workout_programs", "model_version")
    # ### end Alembic commands ###
