"""add training environments and remove profile equipment

Revision ID: 77fcb49685a6
Revises: ebd4d0a4d103
Create Date: 2026-07-15 03:05:22.628266

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77fcb49685a6"
down_revision: Union[str, None] = "ebd4d0a4d103"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

equipment_enum = sa.Enum("HOME", "GYM", "BODYWEIGHT", name="equipment")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_environments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "environment_type",
            sa.Enum("COMMERCIAL_GYM", "HOME", "BODYWEIGHT", "CROSSFIT_BOX", "OTHER", name="environmenttype"),
            nullable=False,
        ),
        sa.Column("equipment_tags", sa.JSON(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_training_environments_user_id"), "training_environments", ["user_id"], unique=False)
    op.drop_column("user_profiles", "equipment")
    # Postgres doesn't drop a named enum type just because its last column
    # was dropped — do it explicitly, or it leaks and blocks recreating it.
    equipment_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Lossy: any training_environments data is discarded on downgrade.
    # Acceptable pre-production (no seed data, no real users yet).
    equipment_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("user_profiles", sa.Column("equipment", equipment_enum, autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_training_environments_user_id"), table_name="training_environments")
    op.drop_table("training_environments")
    sa.Enum(name="environmenttype").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
