"""add exercises

Revision ID: a1b2c3d4e5f6
Revises: 77fcb49685a6
Create Date: 2026-07-15 12:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "77fcb49685a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

body_region_enum = sa.Enum("UPPER_BODY", "LOWER_BODY", "CORE", "FULL_BODY", name="bodyregion")
movement_pattern_enum = sa.Enum(
    "SQUAT",
    "HINGE",
    "LUNGE",
    "HORIZONTAL_PUSH",
    "VERTICAL_PUSH",
    "HORIZONTAL_PULL",
    "VERTICAL_PULL",
    "ROTATION",
    "ANTI_ROTATION",
    "CARRY",
    "ISOLATION",
    "LOCOMOTION",
    "MOBILITY",
    name="movementpattern",
)
# experiencelevel already exists (created in ebd4d0a4d103_initial_schema.py) — reuse it, don't recreate.
# Must use the postgresql-dialect ENUM (not generic sa.Enum): only it honors
# create_type=False during op.create_table, since alembic forces
# checkfirst=False there and generic sa.Enum has no bound metadata to check.
experience_level_enum = postgresql.ENUM(
    "BEGINNER", "INTERMEDIATE", "ADVANCED", name="experiencelevel", create_type=False
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("movement_slug", sa.String(length=255), nullable=False),
        sa.Column("body_region", body_region_enum, nullable=False),
        sa.Column("movement_pattern", movement_pattern_enum, nullable=False),
        sa.Column("primary_muscles", sa.JSON(), nullable=False),
        sa.Column("secondary_muscles", sa.JSON(), nullable=False),
        sa.Column("equipment_tags", sa.JSON(), nullable=False),
        sa.Column("difficulty_level", experience_level_enum, nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("form_cues", sa.JSON(), nullable=False),
        sa.Column("safety_notes", sa.Text(), nullable=True),
        sa.Column("contraindications", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exercises_slug"), "exercises", ["slug"], unique=True)
    op.create_index(op.f("ix_exercises_movement_slug"), "exercises", ["movement_slug"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exercises_movement_slug"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_slug"), table_name="exercises")
    op.drop_table("exercises")
    # experiencelevel is not dropped here — other tables (user_profiles) still depend on it.
    body_region_enum.drop(op.get_bind(), checkfirst=True)
    movement_pattern_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
