"""drop unused slot_rules column

Revision ID: a7c903edb637
Revises: 078b67ea30c8
Create Date: 2026-07-15 22:01:49.463403

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7c903edb637"
down_revision: Union[str, None] = "078b67ea30c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("program_templates", "slot_rules")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "program_templates",
        sa.Column("slot_rules", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
