"""initial schema

Revision ID: ebd4d0a4d103
Revises:
Create Date: 2026-07-09 21:48:58.997856

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebd4d0a4d103"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("gender", sa.String(length=20), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column(
            "activity_level",
            sa.Enum("SEDENTARY", "LIGHTLY_ACTIVE", "MODERATELY_ACTIVE", "VERY_ACTIVE", name="activitylevel"),
            nullable=True,
        ),
        sa.Column(
            "fitness_focus",
            sa.Enum(
                "STRENGTH", "ENDURANCE", "WEIGHT_LOSS", "MUSCLE_GAIN", "FLEXIBILITY", "GENERAL", name="fitnessfocus"
            ),
            nullable=True,
        ),
        sa.Column(
            "experience_level", sa.Enum("BEGINNER", "INTERMEDIATE", "ADVANCED", name="experiencelevel"), nullable=True
        ),
        sa.Column("days_per_week", sa.Integer(), nullable=True),
        sa.Column("workout_duration_min", sa.Integer(), nullable=True),
        sa.Column("equipment", sa.Enum("HOME", "GYM", "BODYWEIGHT", name="equipment"), nullable=True),
        sa.Column("injuries_limitations", sa.Text(), nullable=True),
        sa.Column("short_term_goals", sa.Text(), nullable=True),
        sa.Column("medium_term_goals", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
