PROGRAM_TEMPLATE_SEED: list[dict[str, object]] = [
    {
        "name": "Full Body",
        "slug": "full-body-x3",
        "description": "Three full-body days for beginners building general strength.",
        "goals": ["general", "strength"],
        "experience_levels": ["beginner"],
        "days_per_week_min": 3,
        "days_per_week_max": 3,
        "session_duration_min": 45,
        "session_duration_max": 60,
        "progression_ref": {"model_key": "linear_load", "params": {"increment": 2.5}, "deload_every": 4},
        "required_inputs": [
            {"key": "squat_start", "label": "Comfortable squat weight", "type": "number", "applies_to": "squat"},
            {
                "key": "bench_start",
                "label": "Comfortable bench weight",
                "type": "number",
                "applies_to": "horizontal_push",
            },
        ],
        "split": {
            "schemes": {
                "main": {
                    "sets": 3,
                    "reps_min": 5,
                    "reps_max": 5,
                    "rest_seconds": 120,
                    "target_rpe": 8.0,
                    "intensity_pct": 0.8,
                },
                "accessory": {
                    "sets": 3,
                    "reps_min": 10,
                    "reps_max": 12,
                    "rest_seconds": 60,
                    "target_rpe": 7.0,
                    "intensity_pct": 0.65,
                },
            },
            "sessions": [
                {
                    "key": "full_a",
                    "name": "Full Body A",
                    "order": 1,
                    "slots": [
                        {"pattern": "squat", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_pull", "priority": "primary", "scheme": "main"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "full_b",
                    "name": "Full Body B",
                    "order": 2,
                    "slots": [
                        {"pattern": "hinge", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_pull", "priority": "primary", "scheme": "main"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "full_c",
                    "name": "Full Body C",
                    "order": 3,
                    "slots": [
                        {"pattern": "squat", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_push", "priority": "secondary", "scheme": "accessory"},
                        {"pattern": "horizontal_pull", "priority": "secondary", "scheme": "accessory"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
            ],
        },
    },
    {
        "name": "Bodyweight Full Body",
        "slug": "bodyweight-full-body-x3",
        "description": "Three full-body bodyweight days for beginners with no equipment.",
        "goals": ["general"],
        "experience_levels": ["beginner"],
        "days_per_week_min": 3,
        "days_per_week_max": 3,
        "session_duration_min": 30,
        "session_duration_max": 45,
        "progression_ref": {"model_key": "double_progression", "params": {"increment": 0}},
        "required_inputs": [],
        "split": {
            "schemes": {
                "main": {
                    "sets": 3,
                    "reps_min": 8,
                    "reps_max": 15,
                    "rest_seconds": 90,
                    "target_rpe": 8.0,
                    "intensity_pct": 0.8,
                },
                "accessory": {
                    "sets": 3,
                    "reps_min": 8,
                    "reps_max": 15,
                    "rest_seconds": 60,
                    "target_rpe": 7.0,
                    "intensity_pct": 0.65,
                },
            },
            "sessions": [
                {
                    "key": "full_a",
                    "name": "Full Body A",
                    "order": 1,
                    "slots": [
                        {"pattern": "squat", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_pull", "priority": "primary", "scheme": "main"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "full_b",
                    "name": "Full Body B",
                    "order": 2,
                    "slots": [
                        {"pattern": "squat", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_push", "priority": "secondary", "scheme": "accessory"},
                        {"pattern": "vertical_pull", "priority": "secondary", "scheme": "accessory"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "full_c",
                    "name": "Full Body C",
                    "order": 3,
                    "slots": [
                        {"pattern": "squat", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_pull", "priority": "primary", "scheme": "main"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
            ],
        },
    },
    {
        "name": "Upper / Lower",
        "slug": "upper-lower-x4",
        "description": "Four-day upper/lower split for intermediate lifters building strength and muscle.",
        "goals": ["strength", "muscle_gain"],
        "experience_levels": ["intermediate"],
        "days_per_week_min": 4,
        "days_per_week_max": 4,
        "session_duration_min": 45,
        "session_duration_max": 75,
        "progression_ref": {"model_key": "double_progression", "params": {"increment": 2.5}, "deload_every": 4},
        "required_inputs": [
            {"key": "squat_start", "label": "Comfortable squat weight", "type": "number", "applies_to": "squat"},
            {
                "key": "bench_start",
                "label": "Comfortable bench weight",
                "type": "number",
                "applies_to": "horizontal_push",
            },
        ],
        "split": {
            "schemes": {
                "main": {
                    "sets": 4,
                    "reps_min": 6,
                    "reps_max": 8,
                    "rest_seconds": 120,
                    "target_rpe": 8.0,
                    "intensity_pct": 0.8,
                },
                "accessory": {
                    "sets": 3,
                    "reps_min": 10,
                    "reps_max": 12,
                    "rest_seconds": 75,
                    "target_rpe": 7.0,
                    "intensity_pct": 0.65,
                },
            },
            "sessions": [
                {
                    "key": "upper_a",
                    "name": "Upper A",
                    "order": 1,
                    "slots": [
                        {"pattern": "horizontal_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_pull", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_push", "priority": "secondary", "scheme": "accessory"},
                        {"region": "upper_body", "muscles": ["biceps"], "priority": "accessory", "scheme": "accessory"},
                        {
                            "region": "upper_body",
                            "muscles": ["triceps"],
                            "priority": "accessory",
                            "scheme": "accessory",
                        },
                    ],
                },
                {
                    "key": "lower_a",
                    "name": "Lower A",
                    "order": 2,
                    "slots": [
                        {"pattern": "squat", "priority": "primary", "scheme": "main"},
                        {"pattern": "hinge", "priority": "secondary", "scheme": "accessory"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "upper_b",
                    "name": "Upper B",
                    "order": 3,
                    "slots": [
                        {"pattern": "vertical_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_pull", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_push", "priority": "secondary", "scheme": "accessory"},
                        {
                            "region": "upper_body",
                            "muscles": ["shoulders_anterior", "shoulders_lateral", "shoulders_posterior"],
                            "priority": "accessory",
                            "scheme": "accessory",
                        },
                        {
                            "region": "upper_body",
                            "muscles": ["triceps"],
                            "priority": "accessory",
                            "scheme": "accessory",
                        },
                    ],
                },
                {
                    "key": "lower_b",
                    "name": "Lower B",
                    "order": 4,
                    "slots": [
                        {"pattern": "hinge", "priority": "primary", "scheme": "main"},
                        {"pattern": "squat", "priority": "secondary", "scheme": "accessory"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
            ],
        },
    },
    {
        "name": "Push / Pull / Legs",
        "slug": "push-pull-legs-x6",
        "description": "Six-day push/pull/legs split for intermediate to advanced lifters focused on muscle gain.",
        "goals": ["muscle_gain"],
        "experience_levels": ["intermediate", "advanced"],
        "days_per_week_min": 6,
        "days_per_week_max": 6,
        "session_duration_min": 45,
        "session_duration_max": 75,
        "progression_ref": {"model_key": "double_progression", "params": {"increment": 2.5}, "deload_every": 6},
        "required_inputs": [
            {"key": "squat_start", "label": "Comfortable squat weight", "type": "number", "applies_to": "squat"},
            {
                "key": "bench_start",
                "label": "Comfortable bench weight",
                "type": "number",
                "applies_to": "horizontal_push",
            },
        ],
        "split": {
            "schemes": {
                "main": {
                    "sets": 4,
                    "reps_min": 6,
                    "reps_max": 10,
                    "rest_seconds": 90,
                    "target_rpe": 8.0,
                    "intensity_pct": 0.8,
                },
                "accessory": {
                    "sets": 3,
                    "reps_min": 10,
                    "reps_max": 15,
                    "rest_seconds": 60,
                    "target_rpe": 7.0,
                    "intensity_pct": 0.65,
                },
            },
            "sessions": [
                {
                    "key": "push_a",
                    "name": "Push A",
                    "order": 1,
                    "slots": [
                        {"pattern": "horizontal_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_push", "priority": "primary", "scheme": "main"},
                        {
                            "region": "upper_body",
                            "muscles": ["shoulders_anterior", "shoulders_lateral", "shoulders_posterior"],
                            "priority": "secondary",
                            "scheme": "accessory",
                        },
                        {
                            "region": "upper_body",
                            "muscles": ["triceps"],
                            "priority": "accessory",
                            "scheme": "accessory",
                        },
                    ],
                },
                {
                    "key": "pull_a",
                    "name": "Pull A",
                    "order": 2,
                    "slots": [
                        {"pattern": "horizontal_pull", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_pull", "priority": "primary", "scheme": "main"},
                        {"region": "upper_body", "muscles": ["biceps"], "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "legs_a",
                    "name": "Legs A",
                    "order": 3,
                    "slots": [
                        {"pattern": "squat", "priority": "primary", "scheme": "main"},
                        {"pattern": "hinge", "priority": "secondary", "scheme": "accessory"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "push_b",
                    "name": "Push B",
                    "order": 4,
                    "slots": [
                        {"pattern": "vertical_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_push", "priority": "secondary", "scheme": "accessory"},
                        {
                            "region": "upper_body",
                            "muscles": ["shoulders_anterior", "shoulders_lateral", "shoulders_posterior"],
                            "priority": "accessory",
                            "scheme": "accessory",
                        },
                        {
                            "region": "upper_body",
                            "muscles": ["triceps"],
                            "priority": "accessory",
                            "scheme": "accessory",
                        },
                    ],
                },
                {
                    "key": "pull_b",
                    "name": "Pull B",
                    "order": 5,
                    "slots": [
                        {"pattern": "vertical_pull", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_pull", "priority": "secondary", "scheme": "accessory"},
                        {"region": "upper_body", "muscles": ["biceps"], "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "legs_b",
                    "name": "Legs B",
                    "order": 6,
                    "slots": [
                        {"pattern": "hinge", "priority": "primary", "scheme": "main"},
                        {"pattern": "squat", "priority": "secondary", "scheme": "accessory"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
            ],
        },
    },
    {
        "name": "Full Body (2-Day)",
        "slug": "full-body-x2",
        "description": "Two full-body days a week for beginners with limited time.",
        "goals": ["general", "flexibility"],
        "experience_levels": ["beginner"],
        "days_per_week_min": 2,
        "days_per_week_max": 2,
        "session_duration_min": 30,
        "session_duration_max": 45,
        "progression_ref": {"model_key": "double_progression", "params": {"increment": 0}},
        "required_inputs": [],
        "split": {
            "schemes": {
                "main": {
                    "sets": 3,
                    "reps_min": 8,
                    "reps_max": 12,
                    "rest_seconds": 90,
                    "target_rpe": 7.5,
                    "intensity_pct": 0.7,
                },
                "accessory": {
                    "sets": 2,
                    "reps_min": 10,
                    "reps_max": 15,
                    "rest_seconds": 60,
                    "target_rpe": 7.0,
                    "intensity_pct": 0.6,
                },
            },
            "sessions": [
                {
                    "key": "full_a",
                    "name": "Full Body A",
                    "order": 1,
                    "slots": [
                        {"pattern": "squat", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_pull", "priority": "primary", "scheme": "main"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "full_b",
                    "name": "Full Body B",
                    "order": 2,
                    "slots": [
                        {"pattern": "hinge", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_pull", "priority": "primary", "scheme": "main"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
            ],
        },
    },
    {
        "name": "Full Body Endurance",
        "slug": "full-body-endurance-x3",
        "description": "Three full-body days of higher-rep work for endurance and fat-loss goals.",
        "goals": ["endurance", "weight_loss"],
        "experience_levels": ["beginner"],
        "days_per_week_min": 3,
        "days_per_week_max": 3,
        "session_duration_min": 30,
        "session_duration_max": 45,
        "progression_ref": {"model_key": "double_progression", "params": {"increment": 0}},
        "required_inputs": [],
        "split": {
            "schemes": {
                "main": {
                    "sets": 3,
                    "reps_min": 15,
                    "reps_max": 20,
                    "rest_seconds": 45,
                    "target_rpe": 7.0,
                    "intensity_pct": 0.55,
                },
                "accessory": {
                    "sets": 2,
                    "reps_min": 15,
                    "reps_max": 20,
                    "rest_seconds": 30,
                    "target_rpe": 6.5,
                    "intensity_pct": 0.5,
                },
            },
            "sessions": [
                {
                    "key": "full_a",
                    "name": "Full Body A",
                    "order": 1,
                    "slots": [
                        {"pattern": "squat", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_pull", "priority": "primary", "scheme": "main"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "full_b",
                    "name": "Full Body B",
                    "order": 2,
                    "slots": [
                        {"pattern": "hinge", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_pull", "priority": "primary", "scheme": "main"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "full_c",
                    "name": "Full Body C",
                    "order": 3,
                    "slots": [
                        {"pattern": "squat", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_push", "priority": "secondary", "scheme": "accessory"},
                        {"pattern": "horizontal_pull", "priority": "secondary", "scheme": "accessory"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
            ],
        },
    },
    {
        "name": "Full Body Undulating",
        "slug": "full-body-undulating-x3",
        "description": "Three full-body days a week with wave-style undulating periodization for strength.",
        "goals": ["strength"],
        "experience_levels": ["intermediate"],
        "days_per_week_min": 3,
        "days_per_week_max": 3,
        "session_duration_min": 45,
        "session_duration_max": 60,
        "progression_ref": {
            "model_key": "weekly_undulating",
            "params": {
                "waves": [
                    {"reps": 5, "intensity": 1.0},
                    {"reps": 8, "intensity": 0.85},
                    {"reps": 12, "intensity": 0.7},
                ],
                "increment": 2.5,
            },
            "deload_every": 4,
        },
        "required_inputs": [
            {"key": "squat_start", "label": "Comfortable squat weight", "type": "number", "applies_to": "squat"},
            {
                "key": "bench_start",
                "label": "Comfortable bench weight",
                "type": "number",
                "applies_to": "horizontal_push",
            },
        ],
        "split": {
            "schemes": {
                "main": {
                    "sets": 4,
                    "reps_min": 5,
                    "reps_max": 12,
                    "rest_seconds": 120,
                    "target_rpe": 8.0,
                    "intensity_pct": 0.8,
                },
                "accessory": {
                    "sets": 3,
                    "reps_min": 10,
                    "reps_max": 15,
                    "rest_seconds": 60,
                    "target_rpe": 7.0,
                    "intensity_pct": 0.65,
                },
            },
            "sessions": [
                {
                    "key": "full_a",
                    "name": "Full Body A",
                    "order": 1,
                    "slots": [
                        {"pattern": "squat", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_pull", "priority": "primary", "scheme": "main"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "full_b",
                    "name": "Full Body B",
                    "order": 2,
                    "slots": [
                        {"pattern": "hinge", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_pull", "priority": "primary", "scheme": "main"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "full_c",
                    "name": "Full Body C",
                    "order": 3,
                    "slots": [
                        {"pattern": "squat", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_push", "priority": "secondary", "scheme": "accessory"},
                        {"pattern": "horizontal_pull", "priority": "secondary", "scheme": "accessory"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
            ],
        },
    },
    {
        "name": "Upper / Lower (Advanced)",
        "slug": "upper-lower-advanced-x4",
        "description": "Four-day upper/lower split for advanced lifters chasing heavier strength and muscle gain.",
        "goals": ["strength", "muscle_gain"],
        "experience_levels": ["advanced"],
        "days_per_week_min": 4,
        "days_per_week_max": 4,
        "session_duration_min": 60,
        "session_duration_max": 90,
        "progression_ref": {"model_key": "linear_load", "params": {"increment": 5.0}, "deload_every": 4},
        "required_inputs": [
            {"key": "squat_start", "label": "Comfortable squat weight", "type": "number", "applies_to": "squat"},
            {
                "key": "bench_start",
                "label": "Comfortable bench weight",
                "type": "number",
                "applies_to": "horizontal_push",
            },
        ],
        "split": {
            "schemes": {
                "main": {
                    "sets": 5,
                    "reps_min": 3,
                    "reps_max": 6,
                    "rest_seconds": 180,
                    "target_rpe": 8.5,
                    "intensity_pct": 0.85,
                },
                "accessory": {
                    "sets": 3,
                    "reps_min": 8,
                    "reps_max": 10,
                    "rest_seconds": 90,
                    "target_rpe": 7.5,
                    "intensity_pct": 0.7,
                },
            },
            "sessions": [
                {
                    "key": "upper_a",
                    "name": "Upper A",
                    "order": 1,
                    "slots": [
                        {"pattern": "horizontal_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_pull", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_push", "priority": "secondary", "scheme": "accessory"},
                        {"region": "upper_body", "muscles": ["biceps"], "priority": "accessory", "scheme": "accessory"},
                        {
                            "region": "upper_body",
                            "muscles": ["triceps"],
                            "priority": "accessory",
                            "scheme": "accessory",
                        },
                    ],
                },
                {
                    "key": "lower_a",
                    "name": "Lower A",
                    "order": 2,
                    "slots": [
                        {"pattern": "squat", "priority": "primary", "scheme": "main"},
                        {"pattern": "hinge", "priority": "secondary", "scheme": "accessory"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "upper_b",
                    "name": "Upper B",
                    "order": 3,
                    "slots": [
                        {"pattern": "vertical_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_pull", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_push", "priority": "secondary", "scheme": "accessory"},
                        {
                            "region": "upper_body",
                            "muscles": ["shoulders_anterior", "shoulders_lateral", "shoulders_posterior"],
                            "priority": "accessory",
                            "scheme": "accessory",
                        },
                        {
                            "region": "upper_body",
                            "muscles": ["triceps"],
                            "priority": "accessory",
                            "scheme": "accessory",
                        },
                    ],
                },
                {
                    "key": "lower_b",
                    "name": "Lower B",
                    "order": 4,
                    "slots": [
                        {"pattern": "hinge", "priority": "primary", "scheme": "main"},
                        {"pattern": "squat", "priority": "secondary", "scheme": "accessory"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
            ],
        },
    },
    {
        "name": "Body-Part Split",
        "slug": "body-part-split-x5",
        "description": "Five-day body-part split for advanced lifters prioritizing muscle gain.",
        "goals": ["muscle_gain"],
        "experience_levels": ["advanced"],
        "days_per_week_min": 5,
        "days_per_week_max": 5,
        "session_duration_min": 60,
        "session_duration_max": 90,
        "progression_ref": {"model_key": "double_progression", "params": {"increment": 2.5}, "deload_every": 5},
        "required_inputs": [
            {"key": "squat_start", "label": "Comfortable squat weight", "type": "number", "applies_to": "squat"},
            {
                "key": "bench_start",
                "label": "Comfortable bench weight",
                "type": "number",
                "applies_to": "horizontal_push",
            },
        ],
        "split": {
            "schemes": {
                "main": {
                    "sets": 4,
                    "reps_min": 8,
                    "reps_max": 12,
                    "rest_seconds": 90,
                    "target_rpe": 8.0,
                    "intensity_pct": 0.75,
                },
                "accessory": {
                    "sets": 3,
                    "reps_min": 10,
                    "reps_max": 15,
                    "rest_seconds": 60,
                    "target_rpe": 7.5,
                    "intensity_pct": 0.65,
                },
            },
            "sessions": [
                {
                    "key": "chest_day",
                    "name": "Chest Day",
                    "order": 1,
                    "slots": [
                        {"pattern": "horizontal_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_push", "priority": "secondary", "scheme": "accessory"},
                        {"region": "upper_body", "muscles": ["chest"], "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "back_day",
                    "name": "Back Day",
                    "order": 2,
                    "slots": [
                        {"pattern": "horizontal_pull", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_pull", "priority": "secondary", "scheme": "accessory"},
                        {"region": "upper_body", "muscles": ["traps"], "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "shoulders_day",
                    "name": "Shoulders Day",
                    "order": 3,
                    "slots": [
                        {"pattern": "vertical_push", "priority": "primary", "scheme": "main"},
                        {
                            "region": "upper_body",
                            "muscles": ["shoulders_anterior", "shoulders_lateral", "shoulders_posterior"],
                            "priority": "accessory",
                            "scheme": "accessory",
                        },
                        {
                            "region": "upper_body",
                            "muscles": ["triceps"],
                            "priority": "accessory",
                            "scheme": "accessory",
                        },
                    ],
                },
                {
                    "key": "legs_day",
                    "name": "Legs Day",
                    "order": 4,
                    "slots": [
                        {"pattern": "squat", "priority": "primary", "scheme": "main"},
                        {"pattern": "hinge", "priority": "secondary", "scheme": "accessory"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "arms_day",
                    "name": "Arms Day",
                    "order": 5,
                    "slots": [
                        {"region": "upper_body", "muscles": ["biceps"], "priority": "accessory", "scheme": "accessory"},
                        {
                            "region": "upper_body",
                            "muscles": ["triceps"],
                            "priority": "accessory",
                            "scheme": "accessory",
                        },
                        {
                            "region": "upper_body",
                            "muscles": ["forearms"],
                            "priority": "accessory",
                            "scheme": "accessory",
                        },
                    ],
                },
            ],
        },
    },
    {
        "name": "Powerlifting Strength",
        "slug": "powerlifting-strength-x4",
        "description": "Four-day squat/bench/deadlift/overhead split for intermediate-to-advanced strength goals.",
        "goals": ["strength"],
        "experience_levels": ["intermediate", "advanced"],
        "days_per_week_min": 4,
        "days_per_week_max": 4,
        "session_duration_min": 60,
        "session_duration_max": 90,
        "progression_ref": {"model_key": "linear_load", "params": {"increment": 5.0}, "deload_every": 4},
        "required_inputs": [
            {"key": "squat_start", "label": "Comfortable squat weight", "type": "number", "applies_to": "squat"},
            {
                "key": "bench_start",
                "label": "Comfortable bench weight",
                "type": "number",
                "applies_to": "horizontal_push",
            },
            {
                "key": "deadlift_start",
                "label": "Comfortable deadlift weight",
                "type": "number",
                "applies_to": "hinge",
            },
        ],
        "split": {
            "schemes": {
                "main": {
                    "sets": 5,
                    "reps_min": 1,
                    "reps_max": 5,
                    "rest_seconds": 240,
                    "target_rpe": 9.0,
                    "intensity_pct": 0.88,
                },
                "accessory": {
                    "sets": 3,
                    "reps_min": 8,
                    "reps_max": 10,
                    "rest_seconds": 90,
                    "target_rpe": 7.5,
                    "intensity_pct": 0.7,
                },
            },
            "sessions": [
                {
                    "key": "squat_day",
                    "name": "Squat Day",
                    "order": 1,
                    "slots": [
                        {"pattern": "squat", "priority": "primary", "scheme": "main"},
                        {"pattern": "hinge", "priority": "secondary", "scheme": "accessory"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "bench_day",
                    "name": "Bench Day",
                    "order": 2,
                    "slots": [
                        {"pattern": "horizontal_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "vertical_push", "priority": "secondary", "scheme": "accessory"},
                        {
                            "region": "upper_body",
                            "muscles": ["triceps"],
                            "priority": "accessory",
                            "scheme": "accessory",
                        },
                    ],
                },
                {
                    "key": "deadlift_day",
                    "name": "Deadlift Day",
                    "order": 3,
                    "slots": [
                        {"pattern": "hinge", "priority": "primary", "scheme": "main"},
                        {"pattern": "squat", "priority": "secondary", "scheme": "accessory"},
                        {"region": "core", "priority": "accessory", "scheme": "accessory"},
                    ],
                },
                {
                    "key": "overhead_day",
                    "name": "Overhead Day",
                    "order": 4,
                    "slots": [
                        {"pattern": "vertical_push", "priority": "primary", "scheme": "main"},
                        {"pattern": "horizontal_pull", "priority": "secondary", "scheme": "accessory"},
                        {"region": "upper_body", "muscles": ["biceps"], "priority": "accessory", "scheme": "accessory"},
                    ],
                },
            ],
        },
    },
]
